
quarkus.http.port=8081

kafka.bootstrap.servers=redpanda:9092

# Mapeamento do Canal Reativo do SmallRye para o Redpanda
mp.messaging.outgoing.eletroai-metrics.connector=smallrye-kafka
mp.messaging.outgoing.eletroai-metrics.topic=eletroai-metrics
mp.messaging.outgoing.eletroai-metrics.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.outgoing.eletroai-metrics.retries=3
mp.messaging.outgoing.eletroai-metrics.acks=all
mp.messaging.outgoing.eletroai-metrics.batch.size=65536
mp.messaging.outgoing.eletroai-metrics.linger.ms=5
mp.messaging.outgoing.eletroai-metrics.compression.type=lz4

quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{1}] (%t) %m%n

quarkus.log.console.color.mode=true

quarkus.log.level=INFO

quarkus.swagger-ui.always-include=true

quarkus.log.category."io.smallrye.reactive.messaging.kafka".level=WARN
quarkus.log.category."org.apache.kafka".level=WARN
quarkus.log.category."io.netty".level=WARN