
# Configuração do Servidor HTTP Local (Porta onde o teu serviço vai correr no PC)
quarkus.http.port=8081

# Configuração Global do Kafka (Aponta para o tráfego EXTERNAL do teu Redpanda no NAS)
kafka.bootstrap.servers=192.168.1.151:19092

# Mapeamento do Canal Reativo do SmallRye para o Redpanda
# O nome "eletroai-metrics" dentro das parênteses é o nome do canal interno no teu código Java
mp.messaging.outgoing.eletroai-metrics.connector=smallrye-kafka
mp.messaging.outgoing.eletroai-metrics.topic=eletroai-metrics
# 1. Define o Serializer correto do Jackson para objetos/records
mp.messaging.outgoing.eletroai-metrics.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer